const nodemailer = require('nodemailer');
const { Resend } = require('resend');
const fs = require('fs');
const path = require('path');

// 1. Load environment variables from .env.local
const envPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const match = trimmed.match(/^([^=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        const value = match[2].trim().replace(/^["']|["']$/g, '');
        process.env[key] = value;
      }
    }
  });
}

const gmailUser = process.env.GMAIL_USER;
const gmailPass = process.env.GMAIL_APP_PASSWORD;
const resendApiKey = process.env.RESEND_API_KEY;

console.log('--- EMAIL DISPATCHER CONFIGURATION ---');
console.log('Gmail User:', gmailUser ? gmailUser : 'Not configured');
console.log('Gmail Password Available:', !!gmailPass);
console.log('Resend API Key Available:', !!resendApiKey);
console.log('---------------------------------------\n');

const gmailTransporter = (gmailUser && gmailPass)
  ? nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: gmailUser,
        pass: gmailPass
      }
    })
  : null;

const resend = resendApiKey ? new Resend(resendApiKey) : null;

/**
 * Plantra Labs Luxury Dark HTML Email Wrapper
 */
function wrapHtmlEmail(title, bodyContent) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #070709; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #cbd5e1; -webkit-font-smoothing: antialiased;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #070709; padding: 40px 16px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 620px; background-color: #0f1016; border-radius: 16px; border: 1px solid rgba(139, 92, 246, 0.2); overflow: hidden; box-shadow: 0 20px 40px -15px rgba(0, 0, 0, 0.7), 0 0 50px -10px rgba(124, 58, 237, 0.12);">
          
          <!-- Header Banner -->
          <tr>
            <td style="padding: 28px 36px; background: linear-gradient(135deg, #161224 0%, #0d111e 100%); border-bottom: 1px solid rgba(139, 92, 246, 0.18);">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <div style="font-size: 22px; font-weight: 800; letter-spacing: -0.03em; color: #ffffff;">
                      plantra<span style="color: #a855f7;"> ·</span> labs
                    </div>
                    <div style="font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.12em; color: #94a3b8; margin-top: 4px;">
                      Autonomous Multi-Agent Evaluation Platform • Powered by OmniPanel
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Main Body -->
          <tr>
            <td style="padding: 36px 36px 32px 36px; line-height: 1.65; font-size: 15px; color: #cbd5e1;">
              ${bodyContent}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 24px 36px; background-color: #090a0f; border-top: 1px solid rgba(255, 255, 255, 0.06); font-size: 12px; color: #64748b; line-height: 1.6;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td>
                    <div style="font-weight: 600; color: #94a3b8; font-size: 12px;">
                      Plantra Labs Talent Operations & Systems Engineering
                    </div>
                    <div style="margin-top: 4px; font-size: 11px; color: #64748b;">
                      Plantra Labs, Inc. • Bengaluru HQ · Singapore Hub · London Office
                    </div>
                    <div style="margin-top: 10px; font-size: 10.5px; color: #475569;">
                      This automated message was generated by OmniPanel's autonomous evaluation pipeline. All candidate interactions are processed with deterministic scoring and proctoring telemetry.
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

/**
 * Universal dispatcher
 */
async function sendSampleEmail({ recipientEmail, recipientName, subject, bodyText, htmlContent, caseName }) {
  console.log(`\n======================================================`);
  console.log(`🚀 DISPATCHING: ${caseName}`);
  console.log(`To: ${recipientName} <${recipientEmail}>`);
  console.log(`Subject: ${subject}`);

  let sent = false;

  // 1. Try Gmail SMTP
  if (gmailTransporter && gmailUser) {
    try {
      const info = await gmailTransporter.sendMail({
        from: `"Plantra Labs Talent" <${gmailUser}>`,
        to: recipientEmail,
        subject: subject,
        text: bodyText,
        html: htmlContent
      });
      console.log(`✅ [Gmail SMTP Success] Message ID: ${info.messageId}`);
      sent = true;
    } catch (err) {
      console.warn(`⚠️ [Gmail SMTP Error]: ${err.message}`);
    }
  }

  // 2. Fallback to Resend
  if (!sent && resend) {
    try {
      const resp = await resend.emails.send({
        from: 'Plantra Labs Talent <onboarding@resend.dev>',
        to: recipientEmail,
        subject: subject,
        text: bodyText,
        html: htmlContent
      });
      if (resp.data) {
        console.log(`✅ [Resend Success] ID: ${resp.data.id}`);
        sent = true;
      } else {
        console.warn(`⚠️ [Resend Notice]:`, resp.error);
      }
    } catch (err) {
      console.warn(`⚠️ [Resend Error]: ${err.message}`);
    }
  }

  if (!sent) {
    console.error(`❌ Failed to deliver email for ${caseName}`);
  }
  console.log(`======================================================\n`);
  return sent;
}

// Sleep helper
const sleep = (ms) => new Promise(res => setTimeout(res, ms));

async function main() {
  const candidate = {
    name: 'Madhav Gairola',
    email: 'madhavgairola05@gmail.com'
  };

  const job = {
    title: 'Senior Backend Engineer — Distributed Systems & Real-Time APIs'
  };

  console.log(`Sending 6 sample emails to: ${candidate.name} <${candidate.email}>\n`);

  // =========================================================================
  // CASE 1: APPLICATION RECEIVED
  // =========================================================================
  {
    const subject = `Application Received: ${job.title} at Plantra Labs`;
    const bodyText = `Hi ${candidate.name},

Thank you for applying for the ${job.title} position at Plantra Labs!

We have successfully received your application, resume, and technical portfolios. Our parallel ingestion pipeline is currently correlating your resume, GitHub codecraft, and experience to formulate your personalized evaluation context.

What to Expect Next:
1. Multi-Source Profile Synthesis: Our system synthesizes your engineering background to calibrate relevant architectural domains.
2. 3-Round Autonomous AI Evaluation: Qualified candidates will be invited to our 3-stage interview platform:
   • Round 1: Practical Workspace Assessment (Monaco code editor & system design canvas) [35% Weight]
   • Round 2: Multi-Agent Technical Panel (Lead Architect & Specialist Challenger voice discussion) [50% Weight]
   • Round 3: Engineering Leadership & Cultural Alignment (STAR behavioral assessment) [15% Weight]
3. You will receive an invitation email with your scheduled date, time slot, and your private room lobby link.

Thank you again for your interest in building world-class infrastructure with Plantra Labs.

Warm regards,
The Plantra Labs Talent & Engineering Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="margin-bottom: 20px;">
        <span style="display: inline-block; background-color: rgba(124, 58, 237, 0.15); color: #c084fc; font-weight: 700; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; padding: 5px 12px; border-radius: 9999px; border: 1px solid rgba(168, 85, 247, 0.3);">
          Application Received
        </span>
        <h2 style="font-size: 22px; font-weight: 800; color: #ffffff; margin-top: 12px; margin-bottom: 6px; letter-spacing: -0.02em;">
          We've Received Your Application
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Role: <strong style="color: #e2e8f0;">${job.title}</strong> at Plantra Labs</p>
      </div>

      <p>Hi <strong style="color: #f8fafc;">${candidate.name}</strong>,</p>
      <p>Thank you for your application! We are excited to learn more about your technical experience, engineering craft, and past architectural contributions.</p>
      
      <!-- Next Steps Card -->
      <div style="background-color: #14151f; border: 1px solid rgba(139, 92, 246, 0.2); border-radius: 12px; padding: 22px; margin: 24px 0;">
        <div style="font-weight: 700; color: #ffffff; font-size: 13px; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 12px;">
          OmniPanel 3-Round Evaluation Framework:
        </div>
        
        <table width="100%" cellpadding="0" cellspacing="0" style="font-size: 13px; color: #cbd5e1; line-height: 1.5;">
          <tr>
            <td style="padding: 8px 0; vertical-align: top; width: 28px;">
              <span style="color: #a855f7; font-weight: 800;">01</span>
            </td>
            <td style="padding: 8px 0;">
              <strong style="color: #f1f5f9;">Round 1: Practical Workspace (35% Weight)</strong>
              <div style="font-size: 12px; color: #94a3b8; margin-top: 2px;">Hands-on Monaco code editor & System Design architecture canvas with live test case execution.</div>
            </td>
          </tr>
          <tr>
            <td style="padding: 8px 0; vertical-align: top; width: 28px; border-top: 1px solid rgba(255, 255, 255, 0.05);">
              <span style="color: #60a5fa; font-weight: 800;">02</span>
            </td>
            <td style="padding: 8px 0; border-top: 1px solid rgba(255, 255, 255, 0.05);">
              <strong style="color: #f1f5f9;">Round 2: Multi-Agent Technical Panel (50% Weight)</strong>
              <div style="font-size: 12px; color: #94a3b8; margin-top: 2px;">Dynamic voice discussion with Lead Architect and Specialist Challenger exploring concurrency, scale, and failure modes.</div>
            </td>
          </tr>
          <tr>
            <td style="padding: 8px 0; vertical-align: top; width: 28px; border-top: 1px solid rgba(255, 255, 255, 0.05);">
              <span style="color: #34d399; font-weight: 800;">03</span>
            </td>
            <td style="padding: 8px 0; border-top: 1px solid rgba(255, 255, 255, 0.05);">
              <strong style="color: #f1f5f9;">Round 3: Engineering Leadership & Culture (15% Weight)</strong>
              <div style="font-size: 12px; color: #94a3b8; margin-top: 2px;">Behavioral STAR assessment focusing on incident ownership, system trade-offs, and team collaboration.</div>
            </td>
          </tr>
        </table>
      </div>
      
      <p style="font-size: 14px; color: #94a3b8;">
        If your profile matches our requirements, you will receive an invitation email containing your confirmed slot, calendar invite, and private room lobby link.
      </p>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        Warm regards,<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Talent & Engineering Team</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '1. Application Received'
    });
    await sleep(1500);
  }

  // =========================================================================
  // CASE 2: INTERVIEW INVITATION (3-ROUND BREAKDOWN + GREEN ROOM)
  // =========================================================================
  {
    const scheduledAt = '2026-09-18T10:30:00Z';
    const interviewLink = 'http://localhost:3000/interview/int_demo123';
    const dateObj = new Date(scheduledAt);
    const formattedDate = dateObj.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      timeZone: 'Asia/Kolkata'
    });
    const formattedTime = dateObj.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
      timeZone: 'Asia/Kolkata'
    }) + ' IST';
    const fullDateTime = `${formattedDate} at ${formattedTime}`;

    const startTime = new Date(scheduledAt);
    const endTime = new Date(startTime.getTime() + 45 * 60 * 1000);
    const formatGCalDate = (d) => d.toISOString().replace(/-|:|\.\d+/g, '');
    const dates = `${formatGCalDate(startTime)}/${formatGCalDate(endTime)}`;
    const title = encodeURIComponent(`Plantra Labs AI Interview: ${candidate.name} (${job.title})`);
    const details = encodeURIComponent(
      `Role: ${job.title}\n` +
      `Candidate: ${candidate.name}\n` +
      `Scheduled Time: ${fullDateTime}\n` +
      `Interview Room & Lobby: ${interviewLink}\n\n` +
      `OmniPanel 3-Round Evaluation Agenda:\n` +
      `• Round 1: Practical Workspace (Monaco Code Editor + System Design Canvas) [35%]\n` +
      `• Round 2: Multi-Agent Technical Panel (Lead Architect + Specialist Challenger) [50%]\n` +
      `• Round 3: Engineering Leadership & Cultural Alignment (STAR Behavioral Deep-Dive) [15%]\n\n` +
      `Pre-Flight Instructions:\n` +
      `Open the lobby link 5 minutes prior to check microphone input, live volume visualizer, and camera mirror.`
    );
    const gcalUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${details}`;

    const subject = `Congratulations! You're Selected for an Interview: ${job.title} at Plantra Labs`;

    const bodyText = `Hi ${candidate.name},

Congratulations! We were impressed by your background, codecraft, and engineering trajectory. We are excited to invite you to the next stage of our evaluation process for the ${job.title} position at Plantra Labs.

📅 Confirmed Interview Slot:
${fullDateTime}

🔗 Your Private Interview Room & Lobby Link:
${interviewLink}

📅 Add to Google Calendar:
${gcalUrl}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OMNIPANEL 3-ROUND EVALUATION STRUCTURE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Round 1: Practical Workspace Assessment (35% Weight)
   • Hands-on coding in our live Monaco Editor and architectural diagramming in our System Design Canvas.
   • Real-time test execution and algorithmic problem solving.

2. Round 2: Multi-Agent Technical Architecture Panel (50% Weight)
   • Dynamic voice interview with our Lead Architect (Priya) and Specialist Challenger (Arjun).
   • Deep dive into concurrency, distributed consensus, failure recovery, and architectural trade-offs.

3. Round 3: Engineering Leadership & Cultural Alignment (15% Weight)
   • Behavioral assessment with our Head of Talent (Tara).
   • Explores incident ownership, technical conflict resolution, and team leadership.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⏱️ PRE-FLIGHT GREEN ROOM & HARDWARE CHECK:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
When you open your room link before the scheduled start time:
• A live countdown will display on your screen.
• Use the Green Room to test your camera mirror and speak into your mic to verify the real-time audio volume visualizer.
• The "Join Interview" button unlocks automatically as soon as your scheduled time arrives.

We look forward to meeting you!

Warm regards,
The Plantra Labs Talent & Engineering Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="text-align: center; margin-bottom: 24px;">
        <span style="display: inline-block; background-color: rgba(34, 197, 94, 0.15); color: #4ade80; font-weight: 800; font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; padding: 6px 16px; border-radius: 9999px; border: 1px solid rgba(34, 197, 94, 0.3);">
          ✓ Selected for Interview
        </span>
        <h2 style="font-size: 24px; font-weight: 800; color: #ffffff; margin-top: 14px; margin-bottom: 6px; letter-spacing: -0.02em;">
          You're Invited to Plantra Labs
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Role: <strong style="color: #e2e8f0;">${job.title}</strong></p>
      </div>

      <p>Hi <strong style="color: #ffffff;">${candidate.name}</strong>,</p>
      <p>Congratulations! We were impressed by your background, codecraft, and engineering track record. We are excited to invite you to our 3-round autonomous AI technical evaluation powered by OmniPanel.</p>
      
      <!-- Confirmed Slot Card -->
      <div style="background: linear-gradient(180deg, #151624 0%, #10111a 100%); border: 1px solid rgba(139, 92, 246, 0.3); border-radius: 14px; padding: 26px; text-align: center; margin: 24px 0; box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);">
        <div style="font-size: 11px; font-weight: 700; color: #a855f7; text-transform: uppercase; letter-spacing: 0.1em;">Confirmed Interview Slot</div>
        <div style="font-size: 20px; font-weight: 800; color: #ffffff; margin-top: 6px; letter-spacing: -0.01em;">${formattedDate}</div>
        <div style="font-size: 16px; font-weight: 700; color: #818cf8; margin-top: 2px;">${formattedTime}</div>

        <div style="margin-top: 22px;">
          <a href="${interviewLink}" style="display: inline-block; background: linear-gradient(135deg, #7c3aed 0%, #6366f1 100%); color: #ffffff; font-weight: 700; font-size: 14px; text-decoration: none; padding: 13px 32px; border-radius: 10px; box-shadow: 0 4px 14px rgba(124, 58, 237, 0.4); letter-spacing: 0.02em;">
            Enter Interview Room & Lobby →
          </a>
        </div>

        <div style="margin-top: 16px;">
          <a href="${gcalUrl}" target="_blank" style="font-size: 12px; color: #a855f7; text-decoration: underline; font-weight: 600;">
            + Add to Google Calendar (.ics)
          </a>
        </div>
      </div>

      <!-- 3 Rounds Breakdown -->
      <div style="background-color: #12131c; border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; padding: 22px; margin: 24px 0;">
        <div style="font-size: 12px; font-weight: 700; color: #f8fafc; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 14px;">
          Interview Structure (3 Evaluation Rounds):
        </div>

        <div style="padding: 12px; background-color: rgba(255, 255, 255, 0.02); border-radius: 8px; border: 1px solid rgba(255, 255, 255, 0.05); margin-bottom: 10px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong style="color: #c084fc; font-size: 13px;">Round 1: Practical Workspace Assessment</strong></td>
              <td align="right"><span style="font-size: 11px; font-weight: 700; color: #a855f7; background: rgba(168, 85, 247, 0.15); padding: 2px 8px; border-radius: 4px;">35% Weight</span></td>
            </tr>
          </table>
          <div style="font-size: 12.5px; color: #94a3b8; margin-top: 6px; line-height: 1.5;">
            Monaco code editor & System Design canvas. Implement algorithms, verify edge cases with live test runners, and diagram distributed flows.
          </div>
        </div>

        <div style="padding: 12px; background-color: rgba(255, 255, 255, 0.02); border-radius: 8px; border: 1px solid rgba(255, 255, 255, 0.05); margin-bottom: 10px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong style="color: #60a5fa; font-size: 13px;">Round 2: Multi-Agent Technical Panel</strong></td>
              <td align="right"><span style="font-size: 11px; font-weight: 700; color: #60a5fa; background: rgba(96, 165, 250, 0.15); padding: 2px 8px; border-radius: 4px;">50% Weight</span></td>
            </tr>
          </table>
          <div style="font-size: 12.5px; color: #94a3b8; margin-top: 6px; line-height: 1.5;">
            Interactive voice panel with Lead Architect (Priya) and Specialist Challenger (Arjun) exploring concurrency, distributed consensus, failure modes, and trade-offs.
          </div>
        </div>

        <div style="padding: 12px; background-color: rgba(255, 255, 255, 0.02); border-radius: 8px; border: 1px solid rgba(255, 255, 255, 0.05);">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td><strong style="color: #34d399; font-size: 13px;">Round 3: Leadership & Cultural Alignment</strong></td>
              <td align="right"><span style="font-size: 11px; font-weight: 700; color: #34d399; background: rgba(52, 211, 153, 0.15); padding: 2px 8px; border-radius: 4px;">15% Weight</span></td>
            </tr>
          </table>
          <div style="font-size: 12.5px; color: #94a3b8; margin-top: 6px; line-height: 1.5;">
            STAR behavioral discussion with Head of People (Tara) evaluating incident ownership, architectural philosophy, and cross-functional leadership.
          </div>
        </div>
      </div>

      <!-- Green Room Instructions -->
      <div style="background-color: #0c0d14; border: 1px solid rgba(139, 92, 246, 0.2); border-radius: 10px; padding: 18px; margin: 20px 0; font-size: 13px; color: #94a3b8;">
        <div style="font-weight: 700; color: #f1f5f9; margin-bottom: 6px;">⏱️ Green Room & Hardware Check:</div>
        <div>When you access your room link before the scheduled time, you'll enter the <strong>Green Room</strong>. You can preview your video mirror and speak to test the real-time audio volume visualizer. The <strong>"Join Interview"</strong> CTA will unlock automatically at your confirmed start time.</div>
      </div>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        We look forward to speaking with you!<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Talent & Engineering Team</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '2. Interview Invitation (3-Round Panel)'
    });
    await sleep(1500);
  }

  // =========================================================================
  // CASE 3: SELECTION & FORMAL OFFER NOTIFICATION
  // =========================================================================
  {
    const score = 94;
    const summary = 'Candidate demonstrated exceptional mastery in distributed concurrency, live Monaco coding, sub-50ms streaming pipeline design, and outstanding team leadership alignment.';
    const subject = `Congratulations! Offer & Selection Update: ${job.title} at Plantra Labs`;
    const scoreText = `\nComposite 3-Round Evaluation Score: ${score}/100\n`;

    const bodyText = `Hi ${candidate.name},

Congratulations! We are thrilled to inform you that you have been SELECTED for the ${job.title} position at Plantra Labs!

Our evaluation panel and technical leadership were thoroughly impressed by your performance across all 3 evaluation rounds:
• Round 1: Practical Workspace (Monaco Code Editor & System Design Canvas)
• Round 2: Multi-Agent Technical Panel (Concurrency & Distributed Architecture)
• Round 3: Leadership & Cultural Alignment (STAR Values & System Ownership)
${scoreText}
Panel Evaluation Summary:
"${summary}"

What Happens Next:
1. Formal Offer Letter & Compensation: Our Talent Operations team will reach out within 24–48 hours with comprehensive compensation, equity grant, and start date details.
2. Benefits & Systems Walkthrough: We will schedule a brief call to answer any questions regarding equipment provisioning, healthcare, and engineering roadmap.

Welcome to Plantra Labs! We are excited about the prospect of building groundbreaking infrastructure together.

Warmest congratulations,
The Plantra Labs Leadership & Talent Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="text-align: center; margin-bottom: 24px;">
        <span style="display: inline-block; background-color: rgba(34, 197, 94, 0.15); color: #4ade80; font-weight: 800; font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; padding: 6px 16px; border-radius: 9999px; border: 1px solid rgba(34, 197, 94, 0.3);">
          🎉 Application Selected / Offer Stage
        </span>
        <h2 style="font-size: 24px; font-weight: 800; color: #ffffff; margin-top: 14px; margin-bottom: 6px; letter-spacing: -0.02em;">
          Congratulations! You Have Been Selected
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Role: <strong style="color: #e2e8f0;">${job.title}</strong> at Plantra Labs</p>
      </div>

      <p>Hi <strong style="color: #ffffff;">${candidate.name}</strong>,</p>
      <p>We are delighted to inform you that following your 3-round autonomous assessment across the <strong>Practical Workspace</strong>, <strong>Multi-Agent Technical Panel</strong>, and <strong>Leadership Assessment</strong>, you have been <strong style="color: #4ade80;">selected</strong> for the <strong>${job.title}</strong> role at Plantra Labs!</p>

      <!-- Score & Evaluation Summary Card -->
      <div style="background: linear-gradient(180deg, #0e1c14 0%, #0d1612 100%); border: 1px solid rgba(34, 197, 94, 0.3); border-radius: 14px; padding: 24px; margin: 24px 0;">
        <div style="font-size: 11px; font-weight: 700; color: #4ade80; text-transform: uppercase; letter-spacing: 0.08em;">3-Round Composite Evaluation Score</div>
        <div style="font-size: 32px; font-weight: 800; color: #ffffff; margin-top: 4px; letter-spacing: -0.02em;">${score} <span style="font-size: 16px; color: #86efac; font-weight: 600;">/ 100</span></div>
        <div style="font-size: 13.5px; color: #cbd5e1; margin-top: 8px; line-height: 1.6;">
          ${summary}
        </div>
      </div>

      <!-- Next Steps Card -->
      <div style="background-color: #12131c; border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 10px; padding: 20px; margin: 20px 0; font-size: 13px; color: #cbd5e1;">
        <div style="font-weight: 700; color: #ffffff; margin-bottom: 8px; font-size: 13px;">📋 Next Steps in Your Offer Process:</div>
        <ul style="margin: 0; padding-left: 20px; line-height: 1.7; color: #94a3b8;">
          <li>Our Talent Operations lead will contact you within 24–48 hours with formal compensation, equity package, and onboarding documentation.</li>
          <li>We will schedule a brief offer debrief call to walk through health benefits, equipment setup, and your preferred start date.</li>
        </ul>
      </div>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        Welcome to Plantra Labs! We cannot wait to build together.<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Executive & Engineering Leadership</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '3. Selection & Offer Stage'
    });
    await sleep(1500);
  }

  // =========================================================================
  // CASE 4: PRIORITY TALENT POOL / WAITLIST & ALTERNATIVE ROLES
  // =========================================================================
  {
    const altRoles = [
      'Staff Platform Engineer — Core Cloud Infrastructure',
      'AI Systems & Inference Optimization Engineer',
      'Senior Full Stack Engineer — Next.js & Developer Platform'
    ];
    const rolesList = altRoles.join(', ');
    const reason = 'Candidate demonstrated exceptional algorithmic depth and clean concurrency design. While this specific backend requisition required specialized sub-50ms kernel network drivers, the candidate is strongly recommended for our Core Infrastructure and Inference Platform teams.';

    const subject = `Priority Talent Pool & Alternative Role Allocation: ${job.title} at Plantra Labs`;

    const bodyText = `Hi ${candidate.name},

Thank you for completing our 3-round evaluation process for the ${job.title} position at Plantra Labs.

Our evaluation panel identified significant technical strengths in your performance across the practical workspace and architecture panel. While we have selected a candidate whose immediate experience was a precise match for this opening, our review board has recommended you for our Priority Talent Pool and the following matched alternative positions:
${rolesList}

Review Board Feedback:
"${reason}"

What this means:
• You are placed on our fast-track priority roster for matching requisitions.
• As soon as openings arise for these matched areas, our recruiting leads will reach out to you directly without requiring you to re-take initial assessments.

Thank you again for your time, energy, and engineering codecraft.

Warm regards,
The Plantra Labs Talent & Systems Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="text-align: center; margin-bottom: 24px;">
        <span style="display: inline-block; background-color: rgba(56, 189, 248, 0.15); color: #38bdf8; font-weight: 800; font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; padding: 6px 16px; border-radius: 9999px; border: 1px solid rgba(56, 189, 248, 0.3);">
          💡 Priority Talent Pool
        </span>
        <h2 style="font-size: 22px; font-weight: 800; color: #ffffff; margin-top: 14px; margin-bottom: 6px; letter-spacing: -0.02em;">
          Recommended for Priority Talent Pool
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Target Role: <strong style="color: #e2e8f0;">${job.title}</strong></p>
      </div>

      <p>Hi <strong style="color: #ffffff;">${candidate.name}</strong>,</p>
      <p>Thank you for completing our 3-round autonomous interview process. We were thoroughly impressed by your technical reasoning, communication clarity, and practical problem-solving capabilities.</p>

      <!-- Alternative Roles Box -->
      <div style="background-color: #0f172a; border: 1px solid rgba(56, 189, 248, 0.25); border-radius: 12px; padding: 22px; margin: 24px 0;">
        <div style="font-size: 11px; font-weight: 700; color: #38bdf8; text-transform: uppercase; letter-spacing: 0.08em;">Matched Alternative Positions:</div>
        <div style="font-size: 15px; font-weight: 700; color: #ffffff; margin-top: 6px; line-height: 1.5;">
          ${rolesList}
        </div>
        <div style="font-size: 13px; color: #94a3b8; margin-top: 10px; font-style: italic; border-top: 1px solid rgba(255, 255, 255, 0.06); padding-top: 10px;">
          "${reason}"
        </div>
      </div>

      <p style="font-size: 14px; color: #94a3b8;">
        Our engineering leads have logged your verified scorecard. When new headcount opens for these roles, our talent partners will reach out directly to fast-track your candidacy.
      </p>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        Thank you again for your enthusiasm for building with Plantra Labs.<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Talent Team</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '4. Priority Talent Pool / Waitlist'
    });
    await sleep(1500);
  }

  // =========================================================================
  // CASE 5: APPLICATION STATUS UPDATE / REJECTION
  // =========================================================================
  {
    const stage = 'Round 2: Multi-Agent Technical Panel';
    const reason = 'Candidate demonstrated strong general software concepts, but the panel required deeper production experience handling high-contention distributed database deadlocks and multi-region consensus failover.';
    const stageFormatted = ` after completing the ${stage.toLowerCase()} evaluation`;

    const subject = `Update regarding your application for ${job.title} at Plantra Labs`;

    const bodyText = `Hi ${candidate.name},

Thank you for your interest in Plantra Labs and for the time and energy you invested in applying for the ${job.title} position.

Our review panel evaluated your background and performance thoroughly. We received many exceptional applications, and after careful consideration${stageFormatted}, we have decided not to move forward with your candidacy for this specific opening at this time.

Specific Feedback from the Review Board:
"${reason}"

Please know that this was a difficult decision. We were very impressed by aspects of your engineering craft, and we will keep your profile in our Priority Talent Pool should another opportunity emerge that matches your strengths.

We wish you the absolute best in your ongoing engineering endeavors.

Sincerely,
The Plantra Labs Talent Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="margin-bottom: 20px;">
        <span style="display: inline-block; background-color: rgba(148, 163, 184, 0.12); color: #94a3b8; font-weight: 700; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; padding: 5px 12px; border-radius: 9999px; border: 1px solid rgba(148, 163, 184, 0.2);">
          Application Update
        </span>
        <h2 style="font-size: 22px; font-weight: 800; color: #ffffff; margin-top: 12px; margin-bottom: 6px; letter-spacing: -0.02em;">
          Status Update on Your Application
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Role: <strong style="color: #e2e8f0;">${job.title}</strong></p>
      </div>

      <p>Hi <strong style="color: #f8fafc;">${candidate.name}</strong>,</p>
      <p>Thank you for taking the time to participate in our evaluation process for the <strong>${job.title}</strong> position at Plantra Labs. We truly appreciate the opportunity to learn about your codecraft and background.</p>
      
      <p>We evaluated your submissions carefully alongside a highly competitive pool of candidates. After thorough deliberation${stageFormatted}, our team has decided to proceed with other candidates whose background more specifically aligns with our immediate technical requirements for this specific requisition.</p>

      <div style="background-color: rgba(244, 63, 94, 0.08); border-left: 3px solid #f43f5e; padding: 16px 20px; border-radius: 8px; margin: 22px 0; font-size: 13.5px; color: #fda4af;">
        <div style="font-weight: 700; color: #ffffff; margin-bottom: 4px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em;">Feedback from our Review Board:</div>
        <div style="font-style: italic; line-height: 1.6;">"${reason}"</div>
      </div>

      <p style="font-size: 14px; color: #94a3b8;">
        Please know that this was a difficult choice. We were impressed by your engineering strengths, and we will keep your profile in our talent roster for future opportunities matching your technical trajectory.
      </p>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        We wish you the very best in your engineering journey.<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Talent Team</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '5. Application Status Update / Rejection'
    });
    await sleep(1500);
  }

  // =========================================================================
  // CASE 6: APPLICATION PROCESSING FAILED (ACTION REQUIRED)
  // =========================================================================
  {
    const errorReason = "Google Drive access denied. Please ensure link sharing permissions are set to 'Anyone with the link can view' so our autonomous parser can extract your technical profile.";
    const subject = `Action Required: Issue Processing Your Application for ${job.title}`;

    const bodyText = `Hi ${candidate.name},

Thank you for applying to the ${job.title} position at Plantra Labs.

Unfortunately, our system encountered a technical issue while processing your application materials:
${errorReason}

Because our autonomous evaluation pipeline requires valid profile documents to generate your 3-round interview workspace, your application could not be finalized.

Please verify your resume permissions (e.g., ensure Google Drive sharing is set to 'Anyone with the link can view') or upload a valid text-searchable PDF, and submit your application again at our careers portal.

Best regards,
The Plantra Labs Talent Team`;

    const htmlContent = wrapHtmlEmail(
      subject,
      `
      <div style="margin-bottom: 20px;">
        <span style="display: inline-block; background-color: rgba(239, 68, 68, 0.15); color: #f87171; font-weight: 800; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; padding: 5px 12px; border-radius: 9999px; border: 1px solid rgba(239, 68, 68, 0.3);">
          Action Required
        </span>
        <h2 style="font-size: 22px; font-weight: 800; color: #ffffff; margin-top: 12px; margin-bottom: 6px; letter-spacing: -0.02em;">
          Issue Processing Application
        </h2>
        <p style="font-size: 14px; color: #94a3b8; margin: 0;">Role: <strong style="color: #e2e8f0;">${job.title}</strong></p>
      </div>

      <p>Hi <strong style="color: #f8fafc;">${candidate.name}</strong>,</p>
      <p>Thank you for your interest in the <strong>${job.title}</strong> position at Plantra Labs.</p>
      
      <p>Our extraction engine encountered an issue while parsing your application materials. Because of this, your application could not be finalized:</p>

      <div style="background-color: rgba(239, 68, 68, 0.08); border-left: 3px solid #ef4444; border-radius: 8px; padding: 16px 20px; margin: 20px 0;">
        <div style="font-size: 11px; font-weight: 700; color: #f87171; text-transform: uppercase; letter-spacing: 0.06em;">Issue Details:</div>
        <div style="font-size: 13.5px; color: #fca5a5; margin-top: 4px; font-weight: 500;">
          ${errorReason}
        </div>
      </div>

      <p style="font-size: 14px; color: #94a3b8;">
        Please ensure your Google Drive link is publicly viewable or your uploaded PDF contains readable text, and then <strong>submit your application again</strong>.
      </p>

      <p style="margin-top: 28px; font-size: 14px; color: #94a3b8;">
        We apologize for the inconvenience and look forward to reviewing your updated submission!<br/>
        <strong style="color: #f1f5f9;">The Plantra Labs Talent Team</strong>
      </p>
      `
    );

    await sendSampleEmail({
      recipientEmail: candidate.email,
      recipientName: candidate.name,
      subject,
      bodyText,
      htmlContent,
      caseName: '6. Action Required (Processing Issue)'
    });
  }

  console.log('🎉 All 6 sample emails dispatched successfully to madhavgairola05@gmail.com!');
}

main().catch(err => {
  console.error('Fatal execution error in send_all_samples:', err);
  process.exit(1);
});
